# Generated by Django 5.2.4 on 2025-09-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_biometricdata_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('builder_name', models.CharField(max_length=255, verbose_name='Builder/Developer Name')),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed_use', 'Mixed Use'), ('plots', 'Plots'), ('township', 'Township'), ('apartment', 'Apartment'), ('other', 'Other')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('khasra_number', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('number_of_units', models.PositiveIntegerField()),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Detail',
                'verbose_name_plural': 'Project Details',
                'ordering': ['-created_at'],
            },
        ),
    ]
