# Generated by Django 5.2.4 on 2025-09-18 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_projectdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('visitor_name', models.CharField(max_length=255)),
                ('plot_number', models.CharField(blank=True, max_length=50, null=True)),
                ('visitor_mobile', models.CharField(max_length=15)),
                ('visitor_address', models.TextField(blank=True, null=True)),
                ('visitor_status', models.CharField(choices=[('interested', 'Interested'), ('not_interested', 'Not Interested')], default='interested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='attendance.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='attendance.projectdetail')),
            ],
            options={
                'verbose_name': 'Site Visit',
                'verbose_name_plural': 'Site Visits',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
