# Generated by Django 5.2.4 on 2025-09-18 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_propertybooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybooking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
