# Generated by Django 5.2.4 on 2025-09-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_propertybooking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertybooking',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertybooking',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
