# Generated by Django 5.2.4 on 2025-09-23 05:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_propertybooking_latitude_propertybooking_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_area', models.FloatField(blank=True, null=True)),
                ('property_khasra_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delayed', 'Delayed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('service_date', models.DateField(default=django.utils.timezone.localdate)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_statuses', to='attendance.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_statuses', to='attendance.projectdetail')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='attendance.service')),
            ],
            options={
                'verbose_name': 'Employee Service Status',
                'verbose_name_plural': 'Employee Service Statuses',
                'unique_together': {('employee', 'service', 'project', 'property_name')},
            },
        ),
    ]
