# Generated by Django 5.2.4 on 2025-09-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_service_employeeservicestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeservicestatus',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
