# Generated by Django 5.2.4 on 2025-09-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_employeeservicestatus_expected_completion_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeservicestatus',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='employeeservicestatus',
            index=models.Index(fields=['employee', 'service', 'project', 'property_name'], name='attendance__employe_bebf6d_idx'),
        ),
    ]
