# Generated by Django 5.2.4 on 2025-09-26 10:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_employeereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Manager or employee remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plans', to='attendance.employee')),
            ],
            options={
                'verbose_name': 'Work Plan',
                'verbose_name_plural': 'Work Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Work title / description', max_length=255)),
                ('target_quantity', models.PositiveIntegerField(default=0, help_text='Expected target')),
                ('achieved_quantity', models.PositiveIntegerField(default=0, help_text='Achieved count')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('not_achieved', 'Not Achieved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='attendance.workplan')),
            ],
            options={
                'verbose_name': 'Work Detail',
                'verbose_name_plural': 'Work Details',
                'ordering': ['-created_at'],
            },
        ),
    ]
