# Generated by Django 5.2.4 on 2025-09-26 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_workplan_workdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('not_achieved', 'Not Achieved')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('work_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='attendance.workdetail')),
            ],
        ),
    ]
