# Generated by Django 5.2.4 on 2025-09-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_workprogresslog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workprogresslog',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Work Progress Log', 'verbose_name_plural': 'Work Progress Logs'},
        ),
    ]
