# Generated by Django 5.2.4 on 2025-09-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_alter_workprogresslog_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkProgressLog',
        ),
    ]
